### ISSUE TITLE
Clear out 2022 data: Make a blank website

### ISSUE THREAD

**Issue by benjaoming** [django-denmark/2023.djangoday.dk#1]

**Comment by jvzammit** [comment]
This ready to be closed? Or does this include deployment?

**Comment by benjaoming** [comment]
Yes, this and #2 are fixed now :)

**Comment by jvzammit** [comment]
Thanks @benjaoming was going to look into #2 as it appeared as the only one I could tackle on my own. Sorry I haven't been of much help so far.

**Comment by benjaoming** [comment]
Ah yeah, #2 was a freebie.. it just worked :)
