### ISSUE TITLE
"Conduct" menu item is hidden on mobile

### ISSUE THREAD

**Issue by valberg** [django-denmark/2023.djangoday.dk#11]
Using the "Dark Reader" addon on Firefox on mobile shows that the "Conduct" menu item is moved onto the next line:

![Screenshot_20230117-062155.png](https://user-images.githubusercontent.com/5782/212816626-8d99076b-c6f9-404c-aec9-08c4c0351f2d.png)

**Comment by benjaoming** [comment]
This is fixed but I can't remember when :)

![image](https://github.com/django-denmark/2023.djangoday.dk/assets/374612/d5923781-3208-4ca1-bd8a-4a5683262bc5)
