### ISSUE TITLE
Footer Section Update

### ISSUE THREAD

**Issue by money8203** [django-denmark/2023.djangoday.dk#12]
Footer section can be made more attractive and responsive

**Comment by benjaoming** [comment]
This looks pretty okay to me now! LMK if you have ideas, thanks for opening the issue!

![image](https://github.com/django-denmark/2023.djangoday.dk/assets/374612/d397c72e-6f90-455e-8376-02b72dddc6c5)

**Comment by money8203** [comment]
Django Denmark could be settled in a single line (desktop view)
![image](https://github.com/django-denmark/2023.djangoday.dk/assets/89864818/b8faee1f-7bba-48a0-8a5f-753b139d1cf8)

btw why aren't you using any other CSS framework like tailwind ? The website will look more user friendly

**Comment by benjaoming** [comment]
> btw why aren't you using any other CSS framework like tailwind ? The website will look more user friendly

we're using Bootstrap

https://github.com/django-denmark/2023.djangoday.dk/blob/main/assets/sass/djangoday.scss
