### ISSUE TITLE
Turn "previous events" into a timeline

### ISSUE THREAD

**Issue by benjaoming** [django-denmark/2023.djangoday.dk#6]
Example code: https://bootsnipp.com/snippets/xrKXW

**Comment by jvzammit** [comment]
@benjaoming Might be a stupid question: the current site does not appear to use bootstrap. Or do you intend to "handcraft" the styling yourself?

Otherwise good idea :)

**Comment by benjaoming** [comment]
We do use Bootstrap :)

https://github.com/django-denmark/2023.djangoday.dk/blob/5b776ea1827ffc58ff20e05361561252f0458240/assets/sass/djangoday.scss#L59

**Comment by jvzammit** [comment]
@benjaoming I'm so backend I have no idea how to read .scss files (shame).

Gimme some time to try and give this a go.. i.e. till the end of this weekend 🙏

**Comment by benjaoming** [comment]
.scss files are actually fully CSS compatible - but the pre-processor can do so much more. This is a built-in feature of Hugo, so whenever you do `hugo serve`, it will just compile. It also automatically reloads when you make changes :+1:
